package ar.com.webServices.personas.crud.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.2 2022-06-26T13:06:53.139-03:00
 * Generated source version: 3.5.2
 *
 */
@WebServiceClient(name = "PersonasCrudImplService", wsdlLocation = "file:/C:/Users/mateo/AppData/Local/Temp/tempdir1383485378712678383.tmp/crud_1.wsdl", targetNamespace = "http://webservice.com.ar/")
public class PersonasCrudImplService extends Service {

	public final static URL WSDL_LOCATION;

	public final static QName SERVICE = new QName("http://webservice.com.ar/", "PersonasCrudImplService");
	public final static QName PersonasCrudImplPort = new QName("http://webservice.com.ar/", "PersonasCrudImplPort");
	static {
		URL url = null;
		try {
			url = new URL("file:/C:/Users/mateo/AppData/Local/Temp/tempdir1383485378712678383.tmp/crud_1.wsdl");
		} catch (MalformedURLException e) {
			java.util.logging.Logger.getLogger(PersonasCrudImplService.class.getName()).log(
					java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}",
					"file:/C:/Users/mateo/AppData/Local/Temp/tempdir1383485378712678383.tmp/crud_1.wsdl");
		}
		WSDL_LOCATION = url;
	}

	public PersonasCrudImplService(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public PersonasCrudImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public PersonasCrudImplService() {
		super(WSDL_LOCATION, SERVICE);
	}

	public PersonasCrudImplService(WebServiceFeature... features) {
		super(WSDL_LOCATION, SERVICE, features);
	}

	public PersonasCrudImplService(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, SERVICE, features);
	}

	public PersonasCrudImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 *
	 * @return returns PersonasCrud
	 */
	@WebEndpoint(name = "PersonasCrudImplPort")
	public PersonasCrud getPersonasCrudImplPort() {
		return super.getPort(PersonasCrudImplPort, PersonasCrud.class);
	}

	/**
	 *
	 * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *                 on the proxy. Supported features not in the
	 *                 <code>features</code> parameter will have their default
	 *                 values.
	 * @return returns PersonasCrud
	 */
	@WebEndpoint(name = "PersonasCrudImplPort")
	public PersonasCrud getPersonasCrudImplPort(WebServiceFeature... features) {
		return super.getPort(PersonasCrudImplPort, PersonasCrud.class, features);
	}

}
