
package ar.com.webServices.personas.crud.service;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 3.5.2 2022-06-26T13:06:53.080-03:00
 * Generated source version: 3.5.2
 */

@WebFault(name = "PersonaNotFound", targetNamespace = "http://cxf.com.ar/personas")
public class PersonaNotFoundException extends Exception {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4780805990098753298L;
	private PersonaNotFound faultInfo;

	public PersonaNotFoundException() {
		super();
	}

	public PersonaNotFoundException(String message) {
		super(message);
	}

	public PersonaNotFoundException(String message, java.lang.Throwable cause) {
		super(message, cause);
	}

	public PersonaNotFoundException(String message, PersonaNotFound personaNotFound) {
		super(message);
		this.faultInfo = personaNotFound;
	}

	public PersonaNotFoundException(String message, PersonaNotFound personaNotFound, java.lang.Throwable cause) {
		super(message, cause);
		this.faultInfo = personaNotFound;
	}

	public PersonaNotFound getFaultInfo() {
		return this.faultInfo;
	}
}
