
package ar.com.webServices.personas.crud.service;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 3.5.2 2022-06-26T13:06:53.114-03:00
 * Generated source version: 3.5.2
 */

@WebFault(name = "PersonaRepetida", targetNamespace = "http://cxf.com.ar/personas")
public class PersonaRepetidaException extends Exception {

	/**
	 * 
	 */
	private static final long serialVersionUID = 230801699025255131L;
	private PersonaRepetida faultInfo;

	public PersonaRepetidaException() {
		super();
	}

	public PersonaRepetidaException(String message) {
		super(message);
	}

	public PersonaRepetidaException(String message, java.lang.Throwable cause) {
		super(message, cause);
	}

	public PersonaRepetidaException(String message, PersonaRepetida personaRepetida) {
		super(message);
		this.faultInfo = personaRepetida;
	}

	public PersonaRepetidaException(String message, PersonaRepetida personaRepetida, java.lang.Throwable cause) {
		super(message, cause);
		this.faultInfo = personaRepetida;
	}

	public PersonaRepetida getFaultInfo() {
		return this.faultInfo;
	}
}
